apiVersion: v1
kind: Service
metadata:
  name: apps
  namespace: node-app-ksh
  labels:
    app: nodeapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
  selector:
    app: nodeapp


